/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "linux/jni_md.h"
/* Header for class cx_ath_matthew_unix_UnixServerSocket */

#ifndef _Included_cx_ath_matthew_unix_UnixServerSocket
#define _Included_cx_ath_matthew_unix_UnixServerSocket
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cx_ath_matthew_unix_UnixSocket */

#ifndef _Included_cx_ath_matthew_unix_UnixSocket
#define _Included_cx_ath_matthew_unix_UnixSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cx_ath_matthew_unix_UnixSocket
 * Method:    native_set_pass_cred
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_cx_ath_matthew_unix_UnixSocket_native_1set_1pass_1cred
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     cx_ath_matthew_unix_UnixSocket
 * Method:    native_send_creds
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_cx_ath_matthew_unix_UnixSocket_native_1send_1creds
  (JNIEnv *, jobject, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cx_ath_matthew_unix_USInputStream */

#ifndef _Included_cx_ath_matthew_unix_USInputStream
#define _Included_cx_ath_matthew_unix_USInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef cx_ath_matthew_unix_USInputStream_MAX_SKIP_BUFFER_SIZE
#define cx_ath_matthew_unix_USInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef cx_ath_matthew_unix_USInputStream_MSG_DONTWAIT
#define cx_ath_matthew_unix_USInputStream_MSG_DONTWAIT 64L

#ifdef __cplusplus
}
#endif
#endif
/*
 * Class:     cx_ath_matthew_unix_USInputStream
 * Method:    native_recv
 * Signature: (I[BIIII)I
 */
JNIEXPORT jint JNICALL Java_cx_ath_matthew_unix_USInputStream_native_1recv
        (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint, jint);
/* Header for class cx_ath_matthew_unix_USOutputStream */

#ifndef _Included_cx_ath_matthew_unix_USOutputStream
#define _Included_cx_ath_matthew_unix_USOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cx_ath_matthew_unix_USOutputStream
 * Method:    native_send
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_cx_ath_matthew_unix_USOutputStream_native_1send__I_3BII
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     cx_ath_matthew_unix_USOutputStream
 * Method:    native_send
 * Signature: (I[[B)I
 */
JNIEXPORT jint JNICALL Java_cx_ath_matthew_unix_USOutputStream_native_1send__I_3_3B
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
